---
apiVersion: v1
items:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: fluentd
      name: fluentd
    spec:
      replicas: 1
      selector:
        app: fluentd
        deploymentconfig: fluentd
      template:
        metadata:
          labels:
            app: fluentd
            deploymentconfig: fluentd
        spec:
          containers:
            - image: bcit/openshift-fluentd:latest
              name: fluentd
              ports:
                - containerPort: 5140
                  protocol: TCP
                - containerPort: 24224
                  protocol: TCP
              readinessProbe:
                initialDelaySeconds: 2
                tcpSocket:
                  port: 24224
              volumeMounts:
                - mountPath: /fluentd/etc
                  name: fluentd-etc
                - mountPath: /fluentd/log
                  name: fluentd-log
          volumes:
            - configMap:
                defaultMode: 420
                name: fluentd
              name: fluentd-etc
            - emptyDir: {}
              name: fluentd-log
            }
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: fluentd
      name: fluentd
    spec:
      ports:
        - name: 5140-tcp
          port: 5140
          protocol: TCP
          targetPort: 5140
        - name: 24224-tcp
          port: 24224
          protocol: TCP
          targetPort: 24224
      selector:
        deploymentconfig: fluentd
  - apiVersion: v1
    data:
      fluent.conf: |
        <source>
          @type  forward
          @id    input1
          @label @mainstream
          port  24224
        </source>

        <filter **>
          @type stdout
        </filter>

        <label @mainstream>
          <match docker.**>
            @type file
            @id   output_docker1
            path         /fluentd/log/docker.*.log
            symlink_path /fluentd/log/docker.log
            append       true
            time_slice_format %Y%m%d
            time_slice_wait   1m
            time_format       %Y%m%dT%H%M%S%z
          </match>
          <match **>
            @type file
            @id   output1
            path         /fluentd/log/data.*.log
            symlink_path /fluentd/log/data.log
            append       true
            time_slice_format %Y%m%d
            time_slice_wait   10m
            time_format       %Y%m%dT%H%M%S%z
          </match>
        </label>
    kind: ConfigMap
    metadata:
      name: fluentd
kind: List
metadata: {}
